service: <CHANGE_ME>-aws-workshops-1  # NOTE: update this with your service name

custom:
  bucket_name: "<CHANGE_ME>-aws-workshops-bucket"
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource:
        - "arn:aws:s3:::${self:custom.bucket_name}/*"
        - "arn:aws:s3:::${self:custom.bucket_name}"
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
      Resource:
        - Fn::ImportValue: "<CHANGE_ME>-${self:custom.stage}-queue-arn"

functions:
  scraper:
    handler: handlers.scraper.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [MyQueue, Arn]
          batchSize: 10
    environment:
      BUCKET_NAME: ${self:custom.bucket_name}
  trigger:
    handler: handlers.trigger.handler
    environment:
      QUEUE_NAME:
        Fn::ImportValue: "<CHANGE_ME>-${self:custom.stage}-queue-name"
    events:
      - http:
          path: trigger
          method: get

resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket_name}

plugins:
  - serverless-python-requirements
